// portal_page.h —— 配网门户 HTML/JS 模板（仅 net_portal.c 使用）
//
// 页面结构：顶部通用（WiFi 扫描）+ 双标签页（网络 / 日历）；每条配置逐条增删。
// JS 提交前把列表项编码成后端的 CSV / 分号格式，后端 NVS 代码完全不变。
//
// snprintf 占位顺序：
//   ssid, pass, city, apikey, host, SD_OK(int), INIT_MARKS, INIT_EVENTS, INIT_LABELS
#pragma once

static const char PAGE_TEMPLATE[] =
"<!doctype html><html><head><meta charset=utf-8>"
"<meta name=viewport content='width=device-width,initial-scale=1'>"
"<title>RLCD Setup</title>"
"<style>"
"body{font-family:sans-serif;max-width:440px;margin:20px auto;padding:0 12px}"
"input,select,button{width:100%%;padding:8px;margin:4px 0;box-sizing:border-box;font-size:15px}"
"label{font-weight:bold;display:block;margin:12px 0 4px}"
".btn{padding:10px;font-size:16px}"
".btn.sm{padding:6px 10px;font-size:14px;width:auto}"
".scan{border:1px solid #ccc;border-radius:6px;max-height:180px;overflow:auto;margin-bottom:12px}"
".scan .row{padding:8px 12px;border-bottom:1px solid #eee;cursor:pointer;display:flex;justify-content:space-between}"
".scan .row:hover{background:#f2f7ff}"
".scan .row:last-child{border-bottom:none}"
".lock{color:#888;font-size:12px}"
".hint{color:#888;font-size:12px}"
/* 标签页 */
".tabs{display:flex;border-bottom:2px solid #eee;margin-bottom:16px}"
".tab{padding:8px 16px;cursor:pointer;opacity:.5}"
".tab.active{opacity:1;border-bottom:2px solid #000}"
".page{display:none}"
".page.active{display:block}"
/* 已添加条目：一行 flex，内容占满，删除按钮固定窄 */
".item{display:flex;align-items:center;gap:8px;margin:6px 0;padding:6px 10px;"
      "background:#f6f6f6;border-radius:6px}"
".item .txt{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}"
".item .x{flex:none;width:32px;padding:4px 0;font-size:16px;line-height:1;color:#c00;"
         "background:none;border:1px solid #ddd;border-radius:6px;cursor:pointer}"
/* 添加行：输入占满，按钮固定窄 */
".add{display:flex;gap:8px;align-items:center;margin:6px 0}"
".add input{flex:1;min-width:0;margin:0}"
".add .plus{flex:none;width:64px;margin:0;padding:8px 0}"
".toggle{display:flex;align-items:center;gap:8px;margin:14px 0}"
".toggle input{width:auto;margin:0}"
".disabled{opacity:.4;pointer-events:none}"
"</style></head><body><h2>RLCD Setup</h2>"

/* --- 标签页切换栏（放最上方） --- */
"<div class=tabs>"
"<div class=tab active onclick=\"showTab(0)\">网络与天气</div>"
"<div class=tab onclick=\"showTab(1)\">日历页</div>"
"</div>"

/* ===== 第 0 页：网络与天气（独立 form，保存后重启） ===== */
"<div id=p0 class=page active>"
"<button type=button onclick=\"doScan()\">扫描附近 WiFi</button>"
"<div id=scan class=scan style=\"display:none\"></div>"
"<form method=POST action=/save>"
"<label>WiFi SSID</label><input id=ssid name=ssid value='%s' maxlength=32 required>"
"<label>WiFi Password</label><input name=pass type=password value='%s' maxlength=64>"
"<label>城市 (天气查询用)</label><input name=city value='%s' maxlength=31 placeholder=北京>"
"<label>QWeather API Key</label><input name=apikey value='%s' maxlength=63>"
"<label>QWeather API Host</label>"
"<input name=host value='%s' maxlength=63 placeholder=xxx.re.qweatherapi.com>"
"<button type=submit class=btn style=margin-top:20px>保存网络并重启</button>"
"</form>"
"<p class=hint>保存后设备会重启并加入所选 WiFi。ESP32-S3 只支持 2.4GHz。</p>"
"</div>"

/* ===== 第 1 页：日历页（存 SD 卡，保存后不重启） ===== */
"<div id=p1 class=page>"
"<div id=nosd class=hint style=\"color:#c00;display:none\">未检测到 SD 卡，无法保存日历数据。请插卡后刷新页面。</div>"
"<div id=calbody>"
/* 标记日期 */
"<label>标记日期（日历上黑方块高亮）</label>"
"<div id=marks></div>"
"<div class=add>"
"<input type=date id=new_mark>"
"<button type=button class=\"btn plus\" onclick=\"addMark()\">添加</button>"
"</div>"
/* 预定内容 */
"<hr><label>预定内容（当天底部固定显示的文字）</label>"
"<div id=events></div>"
"<div class=add>"
"<input type=date id=evt_date style=flex:none;width:150px>"
"<input type=text id=evt_text placeholder=内容文字 maxlength=28>"
"<button type=button class=\"btn plus\" onclick=\"addEvent()\">添加</button>"
"</div>"
/* 随机标签 */
"<hr>"
"<div class=toggle>"
"<input type=checkbox id=labels_on onchange=\"toggleLabels()\">"
"<span>启用随机标签（无预定的日子，底部按日期轮选一条）</span>"
"</div>"
"<div id=labels_box style=display:none>"
"<div id=labels></div>"
"<div class=add>"
"<input type=text id=new_label placeholder=标签文字 maxlength=28>"
"<button type=button class=\"btn plus\" onclick=\"addLabel()\">添加</button>"
"</div>"
"</div>"
"<button type=button class=btn style=margin-top:20px onclick=\"saveCal()\">保存日历（写入 SD，不重启）</button>"
"<div id=calmsg class=hint style=margin-top:8px></div>"
"</div>"  /* calbody */
"</div>"  /* p1 */

"<script>"
"var SD_OK=%d;"
"var INIT_MARKS='%s', INIT_EVENTS='%s', INIT_LABELS='%s';"
"var marks=[], events=[], labels=[];"
"function $(id){return document.getElementById(id);}"
"function showTab(n){"
"  document.querySelectorAll('.tab').forEach((t,i)=>t.classList.toggle('active',i==n));"
"  document.querySelectorAll('.page').forEach((p,i)=>p.classList.toggle('active',i==n));"
"}"
"function esc(s){return (''+s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/'/g,'&#39;');}"
/* 通用渲染：list + 取文本函数 → 每行 [内容][删除] */
"function renderBox(id,items,txt){"
"  $(id).innerHTML=items.map((it,i)=>"
"    '<div class=item><span class=txt>'+esc(txt(it))+'</span>'+"
"    '<button type=button class=x onclick=\"del(\\''+id+'\\','+i+')\">×</button></div>').join('');"
"}"
"function del(id,i){({marks:marks,events:events,labels:labels})[id].splice(i,1);renderAll();}"
"function renderAll(){"
"  renderBox('marks',marks,d=>d);"
"  renderBox('events',events,e=>e.date+'  \\u2192  '+e.text);"
"  renderBox('labels',labels,t=>t);"
"}"
"function fmtMMDD(d){return d?d.slice(5):'';}"
"function addMark(){"
"  var v=fmtMMDD($('new_mark').value);"
"  if(!v||marks.indexOf(v)>=0)return;"
"  marks.push(v);marks.sort();$('new_mark').value='';renderAll();"
"}"
"function addEvent(){"
"  var d=fmtMMDD($('evt_date').value),t=$('evt_text').value.trim();"
"  if(!d||!t)return;"
"  for(var i=0;i<events.length;i++)if(events[i].date==d){events[i].text=t;renderAll();return;}"
"  events.push({date:d,text:t});events.sort((a,b)=>a.date<b.date?-1:1);"
"  $('evt_date').value='';$('evt_text').value='';renderAll();"
"}"
"function toggleLabels(){$('labels_box').style.display=$('labels_on').checked?'block':'none';}"
"function addLabel(){"
"  var v=$('new_label').value.trim();"
"  if(!v||labels.indexOf(v)>=0)return;"
"  labels.push(v);$('new_label').value='';renderAll();"
"}"
/* 日历 AJAX 保存到 /save_cal（写 SD，不重启） */
"function saveCal(){"
"  var fd=new URLSearchParams();"
"  fd.append('cal_marks',marks.join(','));"
"  fd.append('cal_events',events.map(e=>e.date+'='+e.text).join(';'));"
"  fd.append('cal_labels',$('labels_on').checked?labels.join(';'):'');"
"  var msg=$('calmsg');msg.style.color='#888';msg.textContent='保存中…';"
"  fetch('/save_cal',{method:'POST',body:fd}).then(r=>r.text().then(t=>({ok:r.ok,t:t}))).then(o=>{"
"    msg.style.color=o.ok?'#080':'#c00';msg.textContent=o.ok?'已保存到 SD 卡':('保存失败：'+o.t);"
"  }).catch(e=>{msg.style.color='#c00';msg.textContent='请求失败：'+e;});"
"}"
/* 初始化：解析 INIT 字符串渲染 */
"function parseMarks(s){return s?s.split(',').filter(x=>x.length>=5).sort():[];}"
"function parseEvents(s){return s?s.split(';').filter(x=>x.indexOf('=')>0).map(p=>{"
"  var i=p.indexOf('=');return {date:p.slice(0,i),text:p.slice(i+1)};"
"}).sort((a,b)=>a.date<b.date?-1:1):[];}"
"function parseLabels(s){return s?s.split(';').filter(x=>x.length>0):[];}"
"marks=parseMarks(INIT_MARKS);events=parseEvents(INIT_EVENTS);labels=parseLabels(INIT_LABELS);"
"$('labels_on').checked=INIT_LABELS.length>0;toggleLabels();renderAll();"
/* 无 SD → 禁用日历编辑 */
"if(!SD_OK){$('nosd').style.display='block';$('calbody').classList.add('disabled');}"
/* WiFi 扫描 */
"function doScan(){"
"  var box=$('scan');box.style.display='block';"
"  box.innerHTML='<div class=row>扫描中…</div>';"
"  fetch('/scan').then(r=>r.json()).then(list=>{"
"    if(!list.length){box.innerHTML='<div class=row>未发现网络</div>';return;}"
"    box.innerHTML=list.map(a=>{"
"      var lock=a.auth?'🔒':'  ';"
"      var bars=a.rssi>-55?'▂▄▆█':a.rssi>-70?'▂▄▆ ':a.rssi>-80?'▂▄  ':'▂   ';"
"      var s=esc(a.ssid);"
"      return \"<div class=row onclick=\\\"pick('\"+s+\"')\\\">\"+"
"        \"<span>\"+lock+' '+s+\"</span><span class=lock>\"+bars+' '+a.rssi+\"dBm</span></div>\";"
"    }).join('');"
"  }).catch(e=>{box.innerHTML='<div class=row>扫描失败：'+e+'</div>';});"
"}"
"function pick(s){$('ssid').value=s;}"
"</script>"

"</body></html>";
